### ISSUE TITLE
Failure to Compile parKVFinder from source

### ISSUE THREAD

**Issue by yuiyep** [LBC-LNBio/parKVFinder#5]
<img width="382" alt="截屏2023-12-18 20 05 56" src="https://github.com/LBC-LNBio/parKVFinder/assets/154231878/8e55283f-defe-46ef-ace7-b8cc6e3389e1">

**Comment by jvsguerra** [comment]
Hi @yuiyep,

It seems the error is indicating that the `gcc-13.2.0` compiler is not found, when you are executing the Makefile. 

It looks like when you were [installing GCC](https://github.com/LBC-LNBio/parKVFinder/wiki/GCC-Installation), you opted to replace `gcc` by `gcc-13.2.0` in the Makefile, but the symbolic link for gcc-13.2.0 is actually `gcc-13`.

```bash
$ gcc-13 --version
gcc-13 (Homebrew GCC 13.2.0) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

If this is the case, you should have used the following command instead:

```bash
$ sed -i -e 's/gcc/gcc-13/' Makefile
```

Also, make sure that the symbolic link for `gcc-13` is correctly set up, or provide the full path to the GCC compiler in the Makefile if needed.

If this was not the case, please, provide some extra information:
- Describe how one can reproduce your parKVFinder installation
- Specify your operating system: [e.g. macOS BigSur,  macOS Monterrey, macOS Ventura, macOS Sonoma]

**Comment by jvsguerra** [comment]
Additionally, we have released a web version of parKVFinder, called **KVFinder-web**. You can access it at https://kvfinder-web.cnpem.br/. For more details, refer to the corresponding article: https://academic.oup.com/nar/article/51/W1/W289/7151338.

**Comment by yuiyep** [comment]
Thanks! It works
